__all__ = [
    'Keywords',
    'Symbols'
]


class Keywords:
    IF = "if"
    ELIF = "elif"
    ELSE = "else"
    FOR = "for"
    IN = "in"
    WHILE = "while"
    DEF = "def"
    CLASS = "class"
    BREAK = "break"
    CONTINUE = "continue"
    RETURN = "return"
    YIELD = "yield"
    RAISE = "raise"
    PASS = "pass"
    OR = "or"
    AND = "and"
    NOT = "not"
    IMPORT = "import"
    AS = "as"
    FROM = "from"
    WITH = "with"

    NONE = "None"
    TRUE = "True"
    FALSE = "False"


class Symbols:
    NEWLINE = "\n"
    INDENT = "    "
    SPACE = " "
    COLON = ":"
    COMMA = ","
    ARROW = "->"
    ELLIPSIS = "..."
    LP = "("
    RP = ")"
    LB = "["
    RB = "]"
    STAR = "*"
    PLUS = "+"
    MINUS = "-"
    SLASH = "/"
    EQUAL = "="
    PERCENT = "%"
    STAR_EQUAL = "*="
    PLUS_EQUAL = "+="
    MINUS_EQUAL = "-="
    SLASH_EQUAL = "/="
    EQUAL_EQUAL = "=="
    PERCENT_EQUAL = "%="
    STAR_STAR = "**"
    SLASH_SLASH = "//"
    SLASH_SLASH_EQUAL = "//="
    EXC_EQUAL = "!="
    LV_EQUAL = "<="
    LV = "<"
    RV_EQUAL = ">="
    RV = ">"
